// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4A8618_Dj4ym7B9ID3ZNfi2EbObGQotE',
    appId: '1:343169331301:web:0c0581b89a728e3a61168c',
    messagingSenderId: '343169331301',
    projectId: 'flutter-app-4ba28',
    authDomain: 'flutter-app-4ba28.firebaseapp.com',
    storageBucket: 'flutter-app-4ba28.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn-P_5d28UEDUpwMlZS3GYLAjaOxWamCg',
    appId: '1:343169331301:android:fb68b042abe1930361168c',
    messagingSenderId: '343169331301',
    projectId: 'flutter-app-4ba28',
    storageBucket: 'flutter-app-4ba28.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLHsyOVH11d3HJ4tl-aZ_4NQ3Udm5Mqs8',
    appId: '1:343169331301:ios:928f01c6bcd4d49e61168c',
    messagingSenderId: '343169331301',
    projectId: 'flutter-app-4ba28',
    storageBucket: 'flutter-app-4ba28.firebasestorage.app',
    iosBundleId: 'com.example.healthAppMain',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLHsyOVH11d3HJ4tl-aZ_4NQ3Udm5Mqs8',
    appId: '1:343169331301:ios:928f01c6bcd4d49e61168c',
    messagingSenderId: '343169331301',
    projectId: 'flutter-app-4ba28',
    storageBucket: 'flutter-app-4ba28.firebasestorage.app',
    iosBundleId: 'com.example.healthAppMain',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4A8618_Dj4ym7B9ID3ZNfi2EbObGQotE',
    appId: '1:343169331301:web:f29edcb63f28e5ed61168c',
    messagingSenderId: '343169331301',
    projectId: 'flutter-app-4ba28',
    authDomain: 'flutter-app-4ba28.firebaseapp.com',
    storageBucket: 'flutter-app-4ba28.firebasestorage.app',
  );
}
